
server:
  port: 8081
  

  
logging.level:
  web: INFO
  root: INFO
  '[com.bptn]': DEBUG
  '[org.hibernate]': INFO
  '[org.hibernate.cfg.annotations.EntityBinder]': DEBUG
  '[org.springframework.beans.factory.support.DefaultListableBeanFactory]': DEBUG
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/feedApp 
    username: postgres
    password: pg123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
 
api:
   key: a970454c5837435a92d5313490c3152d
   base.url: https://newsapi.org/v2/everything